
["custom text"]
	#Insert the custom title screen text you want here (supports multiple lines)
	text = ["§3Industrial MC 2.0", "§3By ghKoty", "§eBased on Create", "Powered by:"]

[versions]
	#Show which version of Minecraft the client is currently running.
	showMcVersion = true
	#Show which version of Minecraft Coder Pack (MCP) the client is running.
	showMcpVersion = false
	#Show which version of Minecraft Forge the client is running.
	showForgeVersion = true
	#Show how many mods are loaded.
	showModsLoaded = false

